### ISSUE TITLE
[Suggestion] List all commands from every mod

### ISSUE THREAD

**Issue by TheDeviantCrafter** [maruohon/tellme#16]
In large modpacks, there can be dozens of even hundreds of commands. Since `/help` lists five at a time, finding the one you want can be tricky. This is especially true if you don't know the exact command, just a general idea of what it does and which mod is supposed to do.

I'd like to have the ability to print all commands to console. It would tell me the command, the mod that adds it, and optionally the parameter structure and `/help` text. I'm not sure if the last two are possible.

**Comment by maruohon** [comment]
I added a `commands` dump today (in 16b4413cd8). However getting the mod name isn't really possible, but I did include the command class name in the dump, which kinda does the same in practice (by grouping the commands by mod, more or less). Example output: https://pastebin.com/raw/ALhQQPi4

It's in this build: https://masa.dy.fi/tmp/minecraft/mods/tellme/tellme-1.12.2-0.7.0-dev.20190219.145540.jar
