### ISSUE TITLE
Commands broken as of Forge 32.0.67

### ISSUE THREAD

**Issue by bessiq** [maruohon/tellme#21]
Hey, I just wanna say this mod is mega-helpful. Thanks for bringing it to 1.16 for Forge _and_ Fabric! 

A recent Forge update [added an event for registering commands](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.1-32.0.71/forge-1.16.1-32.0.71-changelog.txt). Before Forge 32.0.67, non-vanilla commands would stop working after a /reload, including TellMe commands. With Forge 32.0.67 or higher, any command mods that haven't updated cause the game to crash when entering a world. And not having TellMe is terrible! 😭 

Thanks again.

**Comment by maruohon** [comment]
I uploaded a new build to CurseForge, with an update to the command registration change.
