### ISSUE TITLE
[Suggestion] Dump for every item that can break

### ISSUE THREAD

**Issue by Wxrlds** [maruohon/tellme#22]
As the title says, it would be nice to have a dump for every item that can break like Swords, Pickaxes, Helmets,...

**Comment by maruohon** [comment]
Which MC version are you on?

**Comment by Wxrlds** [comment]
Currently 1.16.1 with "tellme-fabric-1.16.1-0.8.1-beta.1" but I think it would be enough to add it for the 1.16.2 update of TellMe (if that ever will be a thing)

**Comment by maruohon** [comment]
A 1.16.2 version will definitely be a thing, but it needs a bunch of more work still due to the changes to biomes and the removal of the old Biome classes.

**Comment by maruohon** [comment]
There is now a `items-damageable` dump in the 0.9.0 version for Forge. I'll have to copy that over to the Fabric version at some point... Here is the output for vanilla items: https://pastebin.com/raw/jC4uBSxr

**Comment by maruohon** [comment]
Actually now that I think about it, I should have added the max damage/durability value to it...

**Comment by maruohon** [comment]
Okay added it to the Fabric version, here is the output with the durabilities also added: https://pastebin.com/raw/UkpG1p4W
