### ISSUE TITLE
[Request] 1.16.3 Forge version (with a missing 1.15 feature)

### ISSUE THREAD

**Issue by bessiq** [maruohon/tellme#23]
Hi there,

I was able to get TellMe working on Forge 34+ by editing the mods.toml file, and it works fine so far - although an official bump to that version would be nice. 😊 

What I've been missing since 1.15 is a certain biome dump feature that would also list the biome types for each biome, e.g. SNOWY, DESERT, SPARSE, etc. There might be a way to still do this with the current 1.16 version, but I can't seem to find it. I know I can get that info for each biome individually, but having a list was super helpful - for me at least!

Anyway, this mod is great and has helped me tinker and figure so many things out. Thanks for making it. 🙂

**Comment by maruohon** [comment]
The BiomeTypes output is now back in the `/tellme biome` output and the `biomes-basic` dump output in version 0.9.0. But the old BiomeDictionary still seems to be gone from Forge. And the default values in the BiomeTypes seem very odd and they are set for only a handful of biomes... (see: https://pastebin.com/raw/Ff1s4rX4)
