### ISSUE TITLE
Commands not working with Command Blocks

### ISSUE THREAD

**Issue by ghost** [maruohon/tellme#26]
Hi,

Is it at all possible to loop commands in the tellme mod? Currently using tellme-fabric-1.16.4-0.9.1-beta.1
 version for Fabric, using 0.11.1 version of the fabric loader and MultiMC, and I'm assuming the mod would work correctly with the 1.16.5 version of minecraft when it works for the 1.16.4 version, unless there were changes to command blocks or something? Anyway, thanks for your help!

I tried with repeating command blocks, but it didn't work:
![image](https://user-images.githubusercontent.com/77590002/108570718-6abea400-72c3-11eb-8b95-447a4e332e83.png)

But it works fine when typed directly into the console:
![image](https://user-images.githubusercontent.com/77590002/108570886-c0934c00-72c3-11eb-8355-8cf23fe5820e.png)

**Comment by maruohon** [comment]
I uploaded version 0.9.2, which fixes this. The commands were set to require OP permission level 4 instead of 2 for some reason, so the command blocks didn't have the permission to run any of the commands.
