### ISSUE TITLE
[Suggest] Option to click on printed output to copy to clipboard

### ISSUE THREAD

**Issue by Vyraal1** [maruohon/tellme#4]
CraftTweaker has a neat functionality where if you click on an ingame text output, you can click to copy it.

https://imgur.com/a/NNWKh

Would it be possible in to implement this with Tell Me? For example I can do /tellme lookingat print while looking at a Skeleton and be able to click on **minecraft:skeleton** ingame to copy it to my clipboard? It seems like a quick and convenient feature in case I don't want a dump of all the files all the time.

**Comment by maruohon** [comment]
This is in version 0.5.6+
