### ISSUE TITLE
[Question] Enchantment dump with level

### ISSUE THREAD

**Issue by ShinryuAspect** [maruohon/tellme#40]
Hi, I was just wondering if there was any way of dumping every enchantment along with its max level.
I know that, technically, those are items (minecraft:enchanted_book) with an NBT associated
```
StoredEnchantments {
  [0] {
    lvl: Xs
    id: "namespace:enchantment_name"
  }
}
```
but I'm struggling to find a way of getting this dump.

EDIT: I found that there was an "items-with-nbt" dump-type lurking in the SubCommandDump.java, but it seems is no longer there on the 1.20.1 branch.

**Comment by maruohon** [comment]
I uploaded a new version where the max lvl was added to the `enchantments` dump.

https://modrinth.com/mod/tellme/version/NiY53paO

**Comment by ShinryuAspect** [comment]
Oh, thank you very much. Such a nice mod for developing I have stumbled upon.
