### ISSUE TITLE
Dump food items

### ISSUE THREAD

**Issue by Watchful1** [maruohon/tellme#8]
A way to dump out a list of all the edible items in the game. Basically just the items list, but add a column with the hunger given and the saturation given, and exclude all items that can't be eaten.

**Comment by maruohon** [comment]
The new dump is `food-items`.

A dev build with this dump included is available at: https://masa.dy.fi/tmp/minecraft/tellme-1.12.2-0.6.0-dev.20180311.004738.jar

**Comment by Watchful1** [comment]
Wow, that was fast. Thanks a bunch Maruohon.

**Comment by maruohon** [comment]
Sorry for the "long" wait, I was in the middle of watching an episode of a TV series :sunglasses:
