### ISSUE TITLE
Error running "blockstats count all-loaded-chunks"

### ISSUE THREAD

**Issue by morrissimo** [maruohon/tellme#9]
Getting an `ArrayOutOfBounds` exception:
https://gist.github.com/morrissimo/11f43e7547ce724e072462efdb70bb49

versions:
* tellme 1.12.2-0.5.6
* forge-1.12.2-14.23.2.2613-universal.jar
* spongeforge-1.12.2-2611-7.1.0-BETA-2953.jar

**Comment by maruohon** [comment]
You must be running the NotEnoughIds mod then, right?

Try this development build, it includes a fix for this (or at least it's supposed to... let me know if it still crashes): https://masa.dy.fi/tmp/minecraft/tellme-1.12.2-0.6.0-dev.20180311.004738.jar

**Comment by morrissimo** [comment]
yep - `NotEnoughIDs` v1.5.4.2 

...naturally I forgot to mention: this is on a server running FTB Revelation v1.5.0

Will try that version shortly and let you know

**Comment by morrissimo** [comment]
looks like it worked - awesome! thanks!

Now, to figure out how to locate a particular type of mod block/tileentity in the world...

**Comment by maruohon** [comment]
This new dev build includes a new `/tellme locate` command that can find blocks, TileEntities or entities from currently loaded chunks. If you need this for unloaded chunks as well, then it is on my TODO list for the World Utils mod, but I don't know when I'll have the time to work on that mod next...

**Comment by morrissimo** [comment]
whoa even more awesome - and no, loaded chunks should be more than sufficient

thanks x2!
